/* Version information autogenerated CMAKE*/
#ifndef  analyse_NAME
#define analyse_NAME "analyse"
#define analyse_VERSION       "HEAD-HASH-NOTFOUND"
#define analyse_MAJOR_VERSION 0
#define analyse_MINOR_VERSION 0
#define analyse_PATCH_VERSION 0
#define BEFORE_analyse(v,r,p) ((analyse_MAJOR_VERSION==(v)&&analyse_MINOR_VERSION==(r)&&analyse_PATCH_VERSION<(p))||(analyse_MAJOR_VERSION==(v)&&analyse_MINOR_VERSION<(r))||(analyse_MAJOR_VERSION<(v)))
#define EQUALS_analyse(v,r,p) (analyse_MAJOR_VERSION==(v)&&analyse_MINOR_VERSION==(r)&&analyse_PATCH_VERSION==(p))
#define analyse_COMPILE_HOST  "lxplus728.cern.ch"
#define analyse_COMPILE_UNAME "Linux lxplus728.cern.ch 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
#define analyse_COMPILE_DIR "/afs/cern.ch/work/l/lgiannes/private/T2K/work/analyse_0.0/cmake"

#endif 

